### ISSUE TITLE
npm-stats syntax error in expression

### ISSUE THREAD

**Issue by Eschon** [jaxgeller/npm-stats#1]
I've tried to run npm-stats after running a few npm commands and I get the following error:

```
-bash: 0+2015-11-02 16:00:15t4: syntax error in expression (error token is "16:00:15t4")
```

Additional Info:
node version 5.0.0
npm version 3.3.6
OS: OSX 10.10.5

**Comment by jaxgeller** [comment]
Can you give me the output of `bash --version`? Also can you give me the output (if possible) of `npm-stats raw`? Thanks

**Comment by jaxgeller** [comment]
Try updating npm-stats now. `cd ~/.npm-stats && git pull` and refresh the shell.

**Comment by Eschon** [comment]
I tried updating but I still get the same error.

bash --version:

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

raw stats:

```
2015-11-02 16:00:15\t4
2015-11-02 16:00:32\t4
2015-11-02 16:00:45\t8
2015-11-02 16:01:34\t42
```

**Comment by jaxgeller** [comment]
I am sorry, I forgot to add that you'll need to get rid of the existing log file `rm ~/.npm-stats/timing`. The problem was that bash was escaping the tab character when it shouldn't have. So for now on it won't escape the tab, but the old occurrences of `\t` are still in the log file.

![image](https://cloud.githubusercontent.com/assets/4494509/10886878/31a967bc-8152-11e5-918b-37a449a73717.png)

**Comment by jaxgeller** [comment]
Hey is this working for you now? May I close this issue?

**Comment by Eschon** [comment]
Works now thanks.
